version: "3.8"

services:
  api-diagnostic-prod:
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    image: 013565464067.dkr.ecr.ap-southeast-2.amazonaws.com/api-diagnostic:latest
    container_name: api-diagnostic-prod
    ports:
      - 9000:8080

  api-diagnostic-dev:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: api-diagnostic-dev:latest
    container_name: api-diagnostic-dev
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 8000:8000